### ISSUE TITLE
Exception on osX

### ISSUE THREAD

**Issue by ignazioc** [YellowApple/tldrb#1]
I installed the gem but when I try to run I receive this error:

```
tldrb foo -o osx
```

```
/Library/Ruby/Gems/2.0.0/gems/bales-0.1.1/lib/bales/application.rb:177:in `const_defined?': wrong constant name Tldrb::Command::Foo (NameError)
    from /Library/Ruby/Gems/2.0.0/gems/bales-0.1.1/lib/bales/application.rb:177:in `block in parse_command_name'
    from /Library/Ruby/Gems/2.0.0/gems/bales-0.1.1/lib/bales/application.rb:169:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/bales-0.1.1/lib/bales/application.rb:169:in `parse_command_name'
    from /Library/Ruby/Gems/2.0.0/gems/bales-0.1.1/lib/bales/application.rb:129:in `parse'
    from /Library/Ruby/Gems/2.0.0/gems/bales-0.1.1/lib/bales/application.rb:159:in `parse_and_run'
    from /Library/Ruby/Gems/2.0.0/gems/tldrb-0.0.1/bin/tldrb:68:in `<class:Application>'
    from /Library/Ruby/Gems/2.0.0/gems/tldrb-0.0.1/bin/tldrb:33:in `<top (required)>'
    from /usr/bin/tldrb:23:in `load'
    from /usr/bin/tldrb:23:in `<main>'
```

**Comment by YellowApple** [comment]
This was an issue with an [underlying library](https://github.com/YellowApple/bales) (which I also happen to maintain, and which I had woefully neglected to test with any Ruby older than 2.2.x).  This has been fixed upstream and here; please install the latest `tldrb` (using the normal `gem install tldrb` method).

Closing this for now.  Thanks for the report, and sorry for not being more diligent about testing real-world environments :/
