### ISSUE TITLE
restclient/request.rb:163:in `fetch': key not found: :ciphers (KeyError)

### ISSUE THREAD

**Issue by soumyaray** [YellowApple/tldrb#9]
Getting this error for any resource I search for:

```
$ tldrb grep

/Users/username/.rvm/gems/ruby-2.4.2/gems/rest-client-1.8.0/lib/restclient/request.rb:163:in `fetch': key not found: :ciphers (KeyError)
	from /Users/username/.rvm/gems/ruby-2.4.2/gems/rest-client-1.8.0/lib/restclient/request.rb:163:in `initialize'
	from /Users/username/.rvm/gems/ruby-2.4.2/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `new'
	from /Users/username/.rvm/gems/ruby-2.4.2/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
	from /Users/username/.rvm/gems/ruby-2.4.2/gems/rest-client-1.8.0/lib/restclient.rb:65:in `get'
	from /Users/username/.rvm/gems/ruby-2.4.2/gems/tldrb-0.0.2/bin/tldrb:12:in `get_page'
	from /Users/username/.rvm/gems/ruby-2.4.2/gems/tldrb-0.0.2/bin/tldrb:57:in `block in <class:Application>'
	from /Users/username/.rvm/gems/ruby-2.4.2/gems/bales-0.1.2/lib/bales/application.rb:120:in `run'
	from /Users/username/.rvm/gems/ruby-2.4.2/gems/bales-0.1.2/lib/bales/application.rb:160:in `parse_and_run'
	from /Users/username/.rvm/gems/ruby-2.4.2/gems/tldrb-0.0.2/bin/tldrb:68:in `<class:Application>'
	from /Users/username/.rvm/gems/ruby-2.4.2/gems/tldrb-0.0.2/bin/tldrb:33:in `<top (required)>'
	from /Users/username/.rvm/gems/ruby-2.4.2/bin/tldrb:23:in `load'
	from /Users/username/.rvm/gems/ruby-2.4.2/bin/tldrb:23:in `<main>'
	from /Users/username/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/username/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by avandecreme** [comment]
Same here

**Comment by YellowApple** [comment]
Well that's weird.

Which OS is this happening under (I'm guessing macOS, but it's worth confirming)?

Also, does the issue persist on `master`?

**Comment by soumyaray** [comment]
@YellowApple sorry I forgot to note:
- MacOS High Sierra 10.13.1
- Ruby 2.4.2 (as seen in the output)

I cloned master and built it using `gem build` to get v0.0.3.  Good news:  No problems there! 

I'll close this issue as I expect you'll push that up to rubygems soon?

**Comment by YellowApple** [comment]
Yep, will do ASAP.  Thanks for the confirmation :)

**Comment by kilasuit** [comment]
get this on Windows with v0.0.2

has v 0.0.3 been pushed to rubygems yet?
